# Generated by Django 2.0.3 on 2018-04-05 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stronapilka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('typ', models.CharField(max_length=30)),
                ('kraj', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mecz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='data meczu')),
                ('gole_gospodarzy', models.IntegerField(default=0)),
                ('gole_gosci', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sedzia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=30)),
                ('typ', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sedzia_mecz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_meczu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stronapilka.Mecz')),
                ('id_sedziego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stronapilka.Sedzia')),
            ],
        ),
        migrations.CreateModel(
            name='Stadion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('kraj', models.CharField(max_length=30)),
                ('pojemnosc', models.IntegerField(default=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('haslo', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('nr_telefonu', models.IntegerField(default=500123456)),
            ],
        ),
        migrations.CreateModel(
            name='Zawodnik_mecz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pozycja', models.CharField(max_length=30)),
                ('id_meczu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stronapilka.Mecz')),
            ],
        ),
        migrations.CreateModel(
            name='Zdarzenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_zdarzenia', models.CharField(max_length=30)),
                ('minuta', models.IntegerField(default=10)),
                ('id_zawodnik_mecz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stronapilka.Zawodnik_mecz')),
            ],
        ),
        migrations.AddField(
            model_name='zawodnik',
            name='id_zespolu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stronapilka.Zespol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zawodnik',
            name='nr_zawodnika_klub',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='zawodnik',
            name='nr_zawodnika_reprezentacja',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='zawodnik',
            name='pozycja',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zespol',
            name='id_stadionu',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='zespol',
            name='kraj',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zespol',
            name='trener',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zawodnik_mecz',
            name='id_zawodnika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stronapilka.Zawodnik'),
        ),
        migrations.AddField(
            model_name='mecz',
            name='id_stadionu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stronapilka.Stadion'),
        ),
        migrations.AddField(
            model_name='liga',
            name='id_zespolu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stronapilka.Zespol'),
        ),
    ]
