# Generated by Django 2.0.3 on 2018-04-05 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stronapilka', '0002_auto_20180405_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goscia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_meczu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stronapilka.Mecz')),
            ],
        ),
        migrations.CreateModel(
            name='Gospodarz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_meczu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stronapilka.Mecz')),
            ],
        ),
        migrations.AlterField(
            model_name='zespol',
            name='id_stadionu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stronapilka.Stadion'),
        ),
        migrations.AddField(
            model_name='gospodarz',
            name='id_zespolu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stronapilka.Zespol'),
        ),
        migrations.AddField(
            model_name='goscia',
            name='id_zespolu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stronapilka.Zespol'),
        ),
    ]
