# Generated by Django 2.0.3 on 2018-04-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stronapilka', '0003_auto_20180405_1216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goscia',
            new_name='Gosc',
        ),
    ]
