# Generated by Django 2.0.3 on 2018-04-05 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stronapilka', '0004_auto_20180405_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liga_zespol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='liga',
            name='id_zespolu',
        ),
        migrations.AddField(
            model_name='liga_zespol',
            name='id_ligi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stronapilka.Liga'),
        ),
        migrations.AddField(
            model_name='liga_zespol',
            name='id_zespolu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stronapilka.Zespol'),
        ),
    ]
