# Generated by Django 2.0.3 on 2018-04-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stronapilka', '0005_auto_20180405_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sedzia',
            name='typ',
            field=models.CharField(choices=[('Glowny', 'Glowny'), ('Liniowy', 'Liniowy'), ('Techniczny', 'Techniczny'), ('Zabramkowy', 'Zabramkowy')], default='Glowny', max_length=30),
        ),
    ]
