# Generated by Django 2.0.3 on 2018-04-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stronapilka', '0006_auto_20180405_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zdarzenie',
            name='typ_zdarzenia',
            field=models.CharField(choices=[('Bramka', 'Bramka'), ('Spalony', 'Spalony'), ('Kontuzja', 'Kontuzja'), ('Zolta kartka', 'Zolta kartka'), ('Czerwona kartka', 'Czerwona kartka'), ('Asysta', 'Asysta'), ('Rzut karny', 'Rzut karny'), ('Niewykorzystany karny', 'Niewykorzystany karny'), ('Rzut wolny', 'Rzut wolny'), ('Zmiana', 'Zmiana')], default='Bramka', max_length=30),
        ),
    ]
