# Generated by Django 2.0.3 on 2018-04-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stronapilka', '0007_auto_20180405_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liga',
            name='typ',
            field=models.CharField(choices=[('Liga', 'Liga'), ('Puchar krajowy', 'Puchar krajowy'), ('Liga mistrzów', 'Liga mistrzów')], default='Liga', max_length=30),
        ),
    ]
