# Generated by Django 2.0.3 on 2018-04-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stronapilka', '0008_auto_20180405_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zawodnik',
            name='pozycja',
            field=models.CharField(choices=[('N', 'N'), ('LN', 'LN'), ('PN', 'PN'), ('LS', 'LS'), ('PS', 'PS'), ('SP', 'SP'), ('SPD', 'SPD'), ('SPO', 'SPO'), ('SN', 'SN'), ('LP', 'LP'), ('PP', 'PP'), ('LO', 'LO'), ('PO', 'PO'), ('SO', 'SO'), ('LW', 'LW'), ('PW', 'PW'), ('BR', 'BR')], default='N', max_length=20),
        ),
    ]
