# Generated by Django 2.0.3 on 2018-04-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stronapilka', '0011_auto_20180405_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mecz',
            name='gole_gosci',
        ),
        migrations.RemoveField(
            model_name='mecz',
            name='gole_gospodarzy',
        ),
        migrations.AddField(
            model_name='gosc',
            name='gole',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gosc',
            name='posiadanie',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='gospodarz',
            name='gole',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gospodarz',
            name='posiadanie',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='gospodarz',
            name='strzaly',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gospodarz',
            name='strzaly_celne',
            field=models.IntegerField(default=0),
        ),
    ]
